### ISSUE TITLE
Should add_trans() function throw exception or resize the automaton?

### ISSUE THREAD

**Issue by tfiedor** [VeriFIT/toris#13]
I am opening this issue for wider discussion. 

Assume the following code:
```
lhs = Nfa();
lhs.add_trans(0,0,0);
```

In previous (Ondra's) implementation, this worked without problems: new transition was made, and `0` was added as a state of `lhs`.

However, the new implementation raises `std::runtime_error: 0 or 0 is not a state`.

Correct code is then:
```
lhs = Nfa(1);
lhs.add_trans(0,0,0);
```
or
```
lhs = Nfa();
lhs.increase_size(1);
lhs.add_trans(0,0,0);
```

The question I am rising is. Would you prefer:
1. Raising the error, if the automaton has not a proper/valid size
2. Quietly resize the automaton to include the new (unregistered) states?

**Comment by martinhruska** [comment]
We discussed it on the meeting and decided that states should not be added in add_trans function. Rationalization:

1. Our data structures are designed for performence and their invariant is that states are a continuous increasing serie of non-negative integers.
2. If user add a transition with a high number of state, it would ruin performance since there would be the same number of transitions as is the number of state.
3. Therefore adding an arbitrary state would go against philosophy of library, which is performance first.
